# -*- coding: utf-8 -*-
#
# Copyright (C) 2021-2023 Graz University of Technology.
#
# repository-cli is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    uses: tu-graz-library/.github/.github/workflows/pypi-publish.yml@main
    secrets: inherit
